include("${CMAKE_CURRENT_LIST_DIR}/../../cmake/MoonShotArchitecture.cmake")

function(check_arch input expected)
    moonshot_normalize_arch("${input}" actual)
    if(NOT actual STREQUAL expected)
        message(FATAL_ERROR "${input}: expected ${expected}, got ${actual}")
    endif()
endfunction()

check_arch(AMD64 x64)
check_arch(x86_64 x64)
check_arch(ARM64 arm64)
check_arch(aarch64 arm64)
check_arch(Win32 x86)
check_arch(i686 x86)
check_arch(armv7l arm)

function(check_target expected)
    moonshot_detect_target_arch(actual)
    if(NOT actual STREQUAL expected)
        message(FATAL_ERROR "Expected target ${expected}, got ${actual}")
    endif()
endfunction()

set(CMAKE_SIZEOF_VOID_P 8)
set(CMAKE_SYSTEM_PROCESSOR ARM64)
set(CMAKE_CXX_COMPILER_ARCHITECTURE_ID x64)
check_target(x64)
set(CMAKE_SYSTEM_PROCESSOR AMD64)
set(CMAKE_CXX_COMPILER_ARCHITECTURE_ID ARM64)
check_target(arm64)
unset(CMAKE_CXX_COMPILER_ARCHITECTURE_ID)
set(CMAKE_VS_PLATFORM_NAME x64)
set(CMAKE_SYSTEM_PROCESSOR ARM64)
check_target(x64)
unset(CMAKE_VS_PLATFORM_NAME)
set(CMAKE_GENERATOR_PLATFORM "x64,version=10.0.26100.0")
check_target(x64)
unset(CMAKE_GENERATOR_PLATFORM)
check_target(arm64)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
set(CMAKE_SIZEOF_VOID_P 4)
check_target(x86)
set(CMAKE_SIZEOF_VOID_P 8)
set(CMAKE_OSX_ARCHITECTURES arm64)
check_target(arm64)
message(STATUS "MoonShot architecture checks passed")
