use icu_segmenter::{options::WordBreakInvariantOptions, WordSegmenter};

pub trait Tokenizer: Send + Sync {
    #[allow(non_snake_case)]
    fn Tokenize(&self, text: &str) -> Vec<String>;
}

/*
* SmartTokenizer — word segmentation via ICU4X WordSegmenter.
* This is the Rust/WASM tokenizer counterpart to C++ MoonShot's ICU
* BreakIterator path. Bigrams are generated by AdvancedIndexWriter at index time.
*/
pub struct SmartTokenizer;

impl SmartTokenizer {
    pub fn new() -> Self { Self }

    #[allow(non_snake_case)]
    fn IsIndexableToken(token: &str) -> bool {
        !token.is_empty()
            && token.len() <= 64
            && !token.chars().any(|ch| {
                ch.is_control()
                    || matches!(ch as u32,
                        0x200B..=0x200F | // zero-width / bidi format controls
                        0x202A..=0x202E | // bidi embeddings/overrides
                        0x2060..=0x206F | // word joiner / invisible operators
                        0xE000..=0xF8FF | // BMP private use
                        0xF0000..=0xFFFFD | // supplementary private use A
                        0x100000..=0x10FFFD) // supplementary private use B
            })
    }
}

impl Default for SmartTokenizer {
    fn default() -> Self { Self::new() }
}

impl Tokenizer for SmartTokenizer {
    fn Tokenize(&self, text: &str) -> Vec<String> {
        if text.is_empty() { return Vec::new(); }

        let segmenter = WordSegmenter::new_auto(WordBreakInvariantOptions::default());
        let mut out = Vec::new();
        let mut prev = 0usize;

        for (boundary, word_type) in segmenter.segment_str(text).iter_with_word_type() {
            if boundary > prev {
                let segment = &text[prev..boundary];
                let keep = word_type.is_word_like()
                    || segment.chars().any(|ch| ch.is_alphanumeric());
                if keep {
                    let token = segment.to_lowercase();
                    if Self::IsIndexableToken(&token) {
                        out.push(token);
                    }
                }
            }
            prev = boundary;
        }

        out
    }
}

#[cfg(test)]
mod tests {
    use super::{SmartTokenizer, Tokenizer};

    #[test]
    fn keeps_cjk_word_segments() {
        let tokenizer = SmartTokenizer::new();
        assert_eq!(tokenizer.Tokenize("学习"), vec!["学习"]);
    }
}
