function(moonshot_normalize_arch architecture output)
    string(TOLOWER "${architecture}" architecture)
    if(architecture MATCHES "^(x64|amd64|x86_64)$")
        set(architecture x64)
    elseif(architecture MATCHES "^(x86|win32|i[3-6]86)$")
        set(architecture x86)
    elseif(architecture MATCHES "^(arm64|aarch64)$")
        set(architecture arm64)
    elseif(architecture MATCHES "^(arm|armv7.*)$")
        set(architecture arm)
    else()
        message(FATAL_ERROR "Unsupported MoonShot target architecture: '${architecture}'")
    endif()
    set(${output} "${architecture}" PARENT_SCOPE)
endfunction()

function(moonshot_detect_target_arch output)
    # Compiler/VS target metadata takes precedence over the host processor.
    if(CMAKE_OSX_ARCHITECTURES)
        list(LENGTH CMAKE_OSX_ARCHITECTURES architecture_count)
        if(NOT architecture_count EQUAL 1)
            message(FATAL_ERROR
                "Use a separate build directory for each macOS architecture; "
                "the Rust executables do not support universal builds.")
        endif()
        set(architecture "${CMAKE_OSX_ARCHITECTURES}")
    elseif(CMAKE_CXX_COMPILER_ARCHITECTURE_ID)
        set(architecture "${CMAKE_CXX_COMPILER_ARCHITECTURE_ID}")
    elseif(CMAKE_VS_PLATFORM_NAME)
        set(architecture "${CMAKE_VS_PLATFORM_NAME}")
    elseif(CMAKE_GENERATOR_PLATFORM)
        string(REGEX REPLACE ",.*$" "" architecture "${CMAKE_GENERATOR_PLATFORM}")
    else()
        set(architecture "${CMAKE_SYSTEM_PROCESSOR}")
    endif()
    moonshot_normalize_arch("${architecture}" architecture)
    if(architecture STREQUAL "x64" AND CMAKE_SIZEOF_VOID_P EQUAL 4)
        set(architecture x86)
    endif()
    set(${output} "${architecture}" PARENT_SCOPE)
endfunction()
